# Practice Problems

In [1]:
import numpy as np

In [2]:
# Create a vector with values ranging from 10 to 49
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [3]:
# Create a vector filled with random values of shape 3x3x3
np.random.random(size=(3,3,3))

array([[[0.92643716, 0.68241223, 0.17840982],
        [0.08438709, 0.14941472, 0.31675193],
        [0.96873987, 0.18418313, 0.27163071]],

       [[0.65625572, 0.94281593, 0.70755035],
        [0.31423757, 0.29259655, 0.04862958],
        [0.6562114 , 0.09294385, 0.92613894]],

       [[0.37891268, 0.11539587, 0.53479198],
        [0.71725645, 0.13916407, 0.20015314],
        [0.17839848, 0.35244643, 0.03860595]]])

In [4]:
a = np.zeros((4,3,3))
np.empty(shape=(3,3,3)) #! Don't use empty over random

array([[[0.92643716, 0.68241223, 0.17840982],
        [0.08438709, 0.14941472, 0.31675193],
        [0.96873987, 0.18418313, 0.27163071]],

       [[0.65625572, 0.94281593, 0.70755035],
        [0.31423757, 0.29259655, 0.04862958],
        [0.6562114 , 0.09294385, 0.92613894]],

       [[0.37891268, 0.11539587, 0.53479198],
        [0.71725645, 0.13916407, 0.20015314],
        [0.17839848, 0.35244643, 0.03860595]]])

In [5]:
# Create a 1d vector and reverse it.
arr = np.arange(10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
# Create a 2D matrix filled with random values and report the matrix max, row max, col max
arr = np.random.randint(low=0, high=10, size=(3,4))
print(arr)

print("Matrix max:", arr.max())
print(f"Row max:", arr.max(axis=1))
print(f"Col max:", arr.max(axis=0))

[[2 2 7 6]
 [9 5 5 9]
 [0 2 0 1]]
Matrix max: 9
Row max: [7 9 2]
Col max: [9 5 7 9]


In [7]:
# Normalization: subtract the mean, divide by the standard deviation
arr = np.random.uniform(low=0, high=10_000, size=(50))
arr_norm = (arr - arr.mean()) / arr.std() # mean=0, std=1

arr_norm.mean(), arr_norm.std()

(-1.9539925233402755e-16, 1.0)

In [8]:
# >>> Homework problem
# Create a 1d array of 100 weights ranging from 1000 to 10_000
# Creata a 1d array of 100 volumes ranging from 10 to 20
# Concatenate the two to get an array of shape (100, 2)
# Normalize the columns

weights = np.random.uniform(low=1_000, high=10_000, size=(100,))
volumes = np.random.uniform(low=10, high=20, size=(100,))
data = np.concatenate([
    np.expand_dims(weights, 1),
    np.expand_dims(volumes, 1),
], axis=1)
print(data.mean(axis=0).round(2), data.std(axis=0).round(2))

data_norm = (data - data.mean(axis=0)) / data.std(axis=0)
print(data_norm.mean(axis=0).round(2), data_norm.std(axis=0).round(2))

[5231.24   15.55] [2912.99    3.01]
[0. 0.] [1. 1.]


In [32]:
# Alternate solution
data = np.vstack([weights, volumes]).T
print(data.mean(axis=0).round(2), data.std(axis=0).round(2))

data_norm = (data - data.mean(axis=0)) / data.std(axis=0)
print(data_norm.mean(axis=0).round(2), data_norm.std(axis=0).round(2))

[5231.24   15.55] [2912.99    3.01]
[ 0. -0.] [1. 1.]


# Conditional Indexing

In [10]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
# Conditional indexing -> Create a boolean mask, use it for indexing
mask = arr % 2 == 0
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False])

In [12]:
arr[mask]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

# Fancy Indexing

In [13]:
arr = np.arange(10, 40, 3)
arr

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [14]:
arr[[2, 6, 3, 1]]

array([16, 28, 19, 13])

In [15]:
list(arr)[[2, 6, 3, 1]]

TypeError: list indices must be integers or slices, not list

In [16]:
# Create an array, `arr`, with of integers 50 to 100.
# Create an array, `random_indices`, of 50 elements with random indices to index `arr`
# Shuffle `arr` using `random_indices`.
arr = np.arange(50, 100)
random_indices = np.random.randint(low=0, high=50, size=50)
print(arr[random_indices])

[77 90 69 95 93 93 86 74 67 76 84 91 99 91 78 55 74 66 97 99 95 51 76 58
 91 69 73 51 63 58 96 55 84 94 81 76 57 72 54 77 50 73 93 82 65 81 97 66
 74 97]


# System of linear equations

In [17]:
# Define the coefficient matrix A.
A = np.array([[2, 4], 
             [6, 8]])

# Define the constant vector b.
b = np.array([5, 6])

# Solve the system of linear equations Ax = b.
x = np.linalg.solve(A, b)

print(x)

[-2.    2.25]


In [18]:
# Manual
np.linalg.inv(A) @ b

array([-2.  ,  2.25])

# Pseudo-randomness

In [19]:
np.random.seed(0) # Seed allows "repeatable" randomness

# No matter how many times this cell is run, it'll always produce the same "random" integer.
np.random.randint(0, 100, 1)

array([44])

In [20]:
# In some jupyter notebooks, previous cell's seed isn't carried to the next cell.
# When using a `random` function in a cell, better reset the seed.
np.random.randint(0, 100, 1)

array([47])

## Choice

In [21]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
# could return duplicates
np.random.randint(low=0, high=len(arr), size=10)

array([64, 67, 67,  9, 83, 21, 36, 87, 70, 88])

In [23]:
# If replace=False, returns unique numbers
np.random.choice(
    a=arr,
    size=10,
    replace=False
)

array([83, 10, 24,  7, 67, 56, 63, 76, 26,  2])

In [24]:
# Sample numbers such that indices 90-99 are thrice more likely to be sampled
probas = np.ones(len(arr))
probas[:90] = 1/120
probas[90:] = 3/120

np.random.choice(
    a=arr,
    size=10,
    replace=False,
    p=probas
)

array([ 6, 54,  2, 53, 99, 43, 57, 82, 95, 96])

In [25]:
## Write a function, that returns probability of elements based on ratio
def cal_probas_given_ratio(r1, r2, n1, n2):
    """
    Calculate the probability that should be assigned to elements given the probablity ratio.
    Example: Some elements should be thrice more likely, r1=1, r2=3, n1=..., n2=...

    Args:
        r1 (int): Probability ratio of n1 elements.
        r2 (int): Probability ratio of n2 elements.
        n1 (int): Elements with ratio r1
        n2 (int): Elements with ratio r2

    Returns:
        (float, float): Probability to be assigned to the n1 and n2 elements respectively.
    """
    x = (n1 * r1) + (n2 * r2)
    return r1/x, r2/x

In [26]:
arr = np.arange(100)

p1, p2 = cal_probas_given_ratio(1, 3, 90, 10)
probas = np.ones(len(arr))
probas[:90] = p1
probas[90:] = p2

np.random.choice(
    a=arr,
    size=10,
    replace=False,
    p=probas
)

array([26, 67, 94, 61, 96,  9, 33,  1, 93, 73])

In [27]:
np.random.choice(
    a=arr,
    size=10,
    replace=False,
)

array([90, 62, 75, 58, 82, 65, 43, 48, 81, 27])

# Shuffle, Permutation

In [28]:
# Shuffle, permutation
print(arr[:10])
np.random.shuffle(arr) # inplace function
print(arr[:10])

# shuffle shuffles input inplace
# it doesn't return anything

[0 1 2 3 4 5 6 7 8 9]
[66 47 93 82 38 74 15 89 64 57]


In [29]:
np.random.permutation(arr)

# permutation shuffles a copy of the input array
# it returns the shuffled array

array([73,  8, 11, 74, 96, 32, 90, 33, 99, 61, 92, 30, 48, 31, 65, 42, 69,
       47, 68, 82, 25, 78, 23, 60, 37, 97, 51, 52, 46, 57, 12, 45, 70, 14,
       79, 91, 84, 29, 76,  1, 98, 83,  5, 58, 55,  2, 93, 19, 20, 94,  4,
       15, 17, 22, 71, 10, 13, 95, 26, 89, 28, 67, 44, 36, 16, 59, 77, 53,
       35, 24, 75,  6,  9, 81, 18, 39,  0, 62, 43, 56,  7, 88, 50, 80,  3,
       63, 72, 21, 41, 86, 54, 27, 85, 38, 87, 49, 34, 40, 64, 66])

# Distributions

In [30]:
rvs = np.random.normal(loc=3, scale=2, size=(20))
rvs

array([ 1.91427705,  3.83210009,  0.68763514,  4.5623962 ,  5.98896909,
       -1.13997005,  3.85251746,  4.35381607,  1.72512595,  2.20545637,
        2.73423884,  2.40441824,  2.38197406, -0.35200761,  5.30466313,
        5.15923718,  1.37327148,  0.06715134,  4.04212975,  1.84842406])

In [31]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the `~numpy.random.Generator.normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
     